### ISSUE TITLE
JupyterLab 3 compatibility

### ISSUE THREAD

**Issue by Tobias-Fischer** [chaitanya-deep/jupyter-amphion#5]
Hi there,
Recently https://github.com/RoboStack/jupyterlab-ros and https://github.com/RoboStack/jupyter-ros were made compatible with JupyterLab3. It would be great to see jupyter-amphion to be compatible with JupyterLab3 as well.
I saw mentioning of an upgrade script and tried briefly, but for some reason it did not work for me out of the box (see https://jupyterlab.readthedocs.io/en/stable/extension/extension_migration.html#upgrading-library-versions-using-the-upgrade-script and https://github.com/RoboStack/jupyter-ros/issues/69). There is probably some other minor manual changes required.

/cc @wolfv @hbcarlos

**Comment by wolfv** [comment]
Hey, thanks for looking into this!

Indeed, our fork here: https://github.com/robostack/jupyter-amphion is jlab 3 compatible :)

**Comment by Tobias-Fischer** [comment]
Ah, how did I miss this? Thanks @wolfv!
